# Verify pull requests on develop.

name: Verify pull requests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  unit-tests-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build and test
        run: ./gradlew check
