# Verify pull requests on develop.

name: Verify pull requests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  unit-tests-pass:
    strategy:
      matrix:
        include:
          - test: jvmTest jsTest linuxX64Test
            os: ubuntu-latest
          - test: macosX64Test macosArm64Test iosSimulatorArm64Test iosX64Test
            os: macos-latest
          - test: mingwX64Test
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Build and test
        run: ./gradlew ${{ matrix.test }}
